In [1]:
#Importing Libraries 
import numpy as np
import pandas as pd

#importing visualization
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
#importing data
data = pd.read_csv('Wine.csv')

In [9]:
data.shape


(178, 14)

In [10]:
data.head()

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    14.23        1.71  2.43          15.6        127           2.80   
1    13.20        1.78  2.14          11.2        100           2.65   
2    13.16        2.36  2.67          18.6        101           2.80   
3    14.37        1.95  2.50          16.8        113           3.85   
4    13.24        2.59  2.87          21.0        118           2.80   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280  Proline  Customer_Segment  
0   3.92     1065                 1  
1   3.40     1050                 1  
2   3.17     1185                 1  
3   3.45     1480                 1  
4   2.93      735                 1

In [3]:
#checking for null values
data.isnull().sum()

Alcohol                 0
Malic_Acid              0
Ash                     0
Ash_Alcanity            0
Magnesium               0
Total_Phenols           0
Flavanoids              0
Nonflavanoid_Phenols    0
Proanthocyanins         0
Color_Intensity         0
Hue                     0
OD280                   0
Proline                 0
Customer_Segment        0
dtype: int64

In [4]:
#importing scale and normalize
from sklearn.preprocessing import scale, normalize

In [5]:
data_scale = scale(data)

C:\Users\abhishek\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.
  """Entry point for launching an IPython kernel.


In [6]:
data_scale

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  1.84791957,
         1.01300893, -1.21394365],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  1.1134493 ,
         0.96524152, -1.21394365],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.78858745,
         1.39514818, -1.21394365],
       ...,
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.48544548,
         0.28057537,  1.37386437],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.40069891,
         0.29649784,  1.37386437],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.42894777,
        -0.59516041,  1.37386437]])

In [8]:
data_normalize = normalize(data_scale)

In [9]:
data_normalize

array([[ 0.36325645, -0.13449175,  0.05550763, ...,  0.44202763,
         0.24231462, -0.29037878],
       [ 0.06849786, -0.13889642, -0.23028162, ...,  0.30967156,
         0.26845214, -0.33762096],
       [ 0.05566736,  0.00600311,  0.31366322, ...,  0.22297234,
         0.3944768 , -0.3432414 ],
       ...,
       [ 0.07325188,  0.38408018, -0.08571094, ..., -0.32699926,
         0.06176459,  0.3024363 ],
       [ 0.0512036 ,  0.05572168,  0.00311582, ..., -0.34278188,
         0.07255955,  0.33621487],
       [ 0.29110327,  0.33034847,  0.28486886, ..., -0.29816896,
        -0.12418814,  0.28667508]])

In [10]:
#importing principal component analysis
from sklearn.decomposition import PCA

In [12]:
model = PCA()

In [13]:
model.fit(data_normalize)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [14]:
model.components_

array([[-0.18410974,  0.19134385, -0.03480568,  0.23089248, -0.12811499,
        -0.3587492 , -0.38450857,  0.27722843, -0.259701  ,  0.04001064,
        -0.24835086, -0.33899065, -0.30316541,  0.4093946 ],
       [-0.46890532, -0.25717696, -0.29706408,  0.03623605, -0.32657952,
        -0.01646084,  0.06003022, -0.05555463,  0.01556664, -0.50676904,
         0.2648361 ,  0.22382876, -0.36463732, -0.02361294],
       [-0.1834544 ,  0.12767015,  0.67183869,  0.5563852 ,  0.1132724 ,
         0.16594487,  0.13796477,  0.19433032,  0.17064192, -0.13715089,
         0.05917827,  0.15793998, -0.12272538, -0.0225512 ],
       [-0.03100299,  0.52534377, -0.25072717,  0.06719469, -0.13854719,
         0.21856242,  0.14536325, -0.32268483,  0.33761177,  0.0668865 ,
        -0.48310016,  0.21279354, -0.23762989,  0.09930927],
       [-0.29504197, -0.32150331, -0.0231602 ,  0.0581738 ,  0.66606329,
        -0.02209321, -0.04025543, -0.47204943,  0.13612562,  0.06684116,
        -0.0612077 , -0.18

In [16]:
#converting 1D to 2D
Componets = pd.DataFrame(model.components_)

In [30]:
Componets 

0         1         2         3         4         5         6   \
0   0.119639  0.024932  0.022865  0.233394  0.947147  0.020058  0.017287   
1  -0.257933 -0.113785 -0.063842 -0.908283  0.261438 -0.028215 -0.013276   
2   0.025332  0.169572 -0.004043 -0.113062  0.045236 -0.130735 -0.243961   
3   0.722610 -0.009028  0.013334 -0.277501 -0.107228  0.240615  0.290077   
4  -0.425241 -0.568195  0.003158  0.155810 -0.075141  0.073594  0.209595   
5  -0.208858  0.707646  0.005441 -0.016388 -0.100206 -0.069991 -0.055955   
6  -0.342223  0.348973  0.024067  0.014484  0.070508  0.320629  0.514518   
7  -0.011747 -0.070082 -0.131816 -0.009269 -0.015087 -0.038673 -0.278052   
8  -0.021195 -0.003178 -0.051807  0.004227  0.006771 -0.555392 -0.237707   
9  -0.205438  0.000716  0.017963 -0.024487 -0.005855  0.524693 -0.368982   
10 -0.074636 -0.001325 -0.005742 -0.034105 -0.003877 -0.462859  0.517198   
11 -0.065760  0.031339  0.727275 -0.047893 -0.005005 -0.098691 -0.028434   
12 -0.042632  0.079166 -0.640961  0.042799  0.002949 -0.026957  0.039727   
13 -0.016688 -0.005630 -0.185506 -0.003629  0.001576  0.027069  0.065029   

          7         8         9         10        11        12        13  
0   0.003976  0.014375  0.024035  0.009837  0.025779 -0.173146  0.027186  
1  -0.018878 -0.020820 -0.103670 -0.008022 -0.048384 -0.038894 -0.081810  
2   0.009732 -0.094280  0.860282 -0.076247 -0.244849  0.193669  0.163736  
3  -0.003583  0.142396  0.235856  0.066871  0.254549 -0.319042 -0.007636  
4  -0.023589  0.051622  0.366135 -0.007399  0.003807 -0.512548 -0.130366  
5  -0.005320 -0.020161 -0.032672 -0.078993 -0.067310 -0.651204 -0.030128  
6  -0.034331  0.352399  0.188353 -0.042868  0.234438  0.368740 -0.184935  
7   0.012330  0.877885 -0.059071  0.014903 -0.142248 -0.068859  0.314534  
8   0.017742  0.122585  0.114206 -0.049371  0.718078  0.017472 -0.291658  
9  -0.004378 -0.189027  0.024266  0.069594  0.512412 -0.035773  0.490265  
10 -0.046755 -0.092150 -0.033670 -0.009626  0.115804 -0.008922  0.697202  
11  0.224953  0.084561  0.029211  0.627558 -0.019509 -0.003400 -0.008254  
12 -0.029134 -0.072044  0.057000  0.751489 -0.019910  0.005116 -0.049924  
13  0.971407 -0.025808 -0.002396 -0.123538  0.010849 -0.005240  0.024279

In [17]:
value = model.explained_variance_ratio_

In [18]:
value.sum()

1.0

In [19]:
value.mean()

0.07142857142857142